name: check-label-preview-env

on:
  pull_request:
    types: [labeled]

jobs:
  check-label-preview-env:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'preview-environment')
    steps:
    - name: Set PR
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        echo "$PR_NUMBER" > pr.txt
    - name: Save PR
      uses: actions/upload-artifact@v2
      with:
        name: pr.txt
        path: |
          pr.txt
